set shortmess=atI  
set nu             
set go=             
set guifont=msyh:h10:cANSI  
syntax on          
autocmd InsertLeave * se nocul
autocmd InsertEnter * se cul    
set ruler          
set showcmd        
set cmdheight=1      
set scrolloff=3     
set novisualbell   
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
set laststatus=2  
set foldenable
set foldmethod=manual
colorscheme desert
set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
"set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936
set fileencoding=utf-8
set completeopt=preview,menu 
filetype plugin on
set nobackup
set autowrite
set ruler                
set cursorline            
set guioptions-=T          
set guioptions-=m          
set foldcolumn=0
set foldmethod=indent 
set foldlevel=3 
set foldenable             
set noeb
set confirm
set autoindent
set cindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab
set number
set history=1000
set nobackup
set noswapfile
set ignorecase
set hlsearch
set incsearch
set gdefault
set langmenu=us_EN.UTF-8
set helplang=en
filetype on
filetype plugin on
filetype indent on
set viminfo+=!
set iskeyword+=_,$,@,%,#,-
set linespace=0
set wildmenu
set backspace=2
set whichwrap+=<,>,h,l
set selection=exclusive
set report=0
set fillchars=vert:\ ,stl:\ ,stlnc:\
set showmatch
set matchtime=1
set scrolloff=3
set smartindent
au BufRead,BufNewFile *  setfiletype txt
:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {<CR>}<ESC>O
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>
function! ClosePair(char)
    if getline('.')[col('.') - 1] == a:char
        return "\<Right>"
    else
        return a:char
    endif
endfunction
filetype plugin indent on 
set completeopt=longest,menu
let Tlist_Sort_Type = "name"    
let Tlist_Use_Right_Window = 1 
let Tlist_Compart_Format = 1  
let Tlist_Exist_OnlyWindow = 1
let Tlist_File_Fold_Auto_Close = 0  
let Tlist_Enable_Fold_Column = 0   
autocmd FileType java set tags+=D:\tools\java\tags  
set tags=tags  
let Tlist_Auto_Open=1 
let Tlist_Ctags_Cmd = '/usr/bin/ctags' 
let Tlist_Show_One_File = 1 
let Tlist_Exit_OnlyWindow = 1 
let Tlist_Use_Right_Window = 1
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1
let b:javascript_fold = 1
let javascript_enable_domhtmlcss = 1
hi TabLine term=underline cterm=bold ctermfg=9 ctermbg=4
hi TabLineSel term=bold cterm=bold ctermbg=red ctermfg=yellow
highlight Pmenu ctermbg=darkred
highlight PmenuSel ctermbg=red ctermfg=white
set ffs=unix,dos,mac
set ff=unix 
set nobomb 
set linebreak
set formatoptions=tcoqmM

